[package]
name = "gc-arena"
version = "0.1.0"
authors = ["kyren <kerriganw@gmail.com>"]
edition = "2018"

[dependencies]
gc-arena-derive = { path = "./gc-arena-derive" }

[dev-dependencies]
rand = "0.5"